name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3.'
inputs:
  bucket:
    description: 'AWS S3 bucket'
    required: true
  bucket-region:
    description: 'AWS S3 bucket region'
    required: false
    default: 'ap-southeast-2'
  dist-folder:
    description: 'folder contains deployable files'
    required: true
outputs:
  website-url: 
    description: 'url of website'
runs:
  using: 'node16'
  main: 'main.js'